---
- hosts: demo
  become: yes
  connection: ssh
  user: pradnyesh
  tasks:
    - name: Start the container
      docker_container:
        name: hariapp
        image: "pradnyeo/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8090:8080
