---
- hosts: dev
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: sunilapp
        image: "sunilvasu/sunilapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
